### ISSUE TITLE
Could thermald be the cause of this crash?

### ISSUE THREAD

**Issue by wil93** [intel/thermal_daemon#48]
( see also https://bbs.archlinux.org/viewtopic.php?pid=1495613 )

Lately my laptop started freezing. For example, I am watching a video (VCL, youtube, doesn't matter..) and sometimes my laptop will just hang, endlessly repeating the last second (or so) of audio (while the video, as well as the mouse pointer and everything else, is stuck). It also happens when I am literally doing nothing (I go back to the laptop after being away and it's stuck).

I am wondering if thermald may be the cause. I use Archlinux, this is the log from journalctl before the forced shutdown:

```
...
Jan 23 22:16:06 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:06 wil93-arch thermald[1764]: set cdev state index 9 state 7000000 wr:28000000
Jan 23 22:16:06 wil93-arch thermald[1764]: Set : 87000, 86000, 9, 7000000, 26250000
Jan 23 22:16:10 wil93-arch thermald[1764]: set cdev state index 9 state 5250000 wr:29750000
Jan 23 22:16:10 wil93-arch thermald[1764]: Set : 93500, 87000, 9, 5250000, 26250000
Jan 23 22:16:10 wil93-arch thermald[1764]: set cdev state index 9 state 7000000 wr:28000000
Jan 23 22:16:10 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 7000000, 26250000
Jan 23 22:16:14 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:14 wil93-arch thermald[1764]: consecutive call, increment exponentially state 10500000
Jan 23 22:16:14 wil93-arch thermald[1764]: set cdev state index 9 state 10500000 wr:24500000
Jan 23 22:16:14 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 10500000, 26250000
Jan 23 22:16:18 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:18 wil93-arch thermald[1764]: consecutive call, increment exponentially state 14000000
Jan 23 22:16:18 wil93-arch thermald[1764]: set cdev state index 9 state 14000000 wr:21000000
Jan 23 22:16:18 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 14000000, 26250000
Jan 23 22:16:22 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:22 wil93-arch thermald[1764]: set cdev state index 9 state 12250000 wr:22750000
Jan 23 22:16:22 wil93-arch thermald[1764]: Set : 87000, 86000, 9, 12250000, 26250000
Jan 23 22:16:26 wil93-arch thermald[1764]: set cdev state index 9 state 10500000 wr:24500000
Jan 23 22:16:26 wil93-arch thermald[1764]: Set : 93500, 86000, 9, 10500000, 26250000
Jan 23 22:16:30 wil93-arch thermald[1764]: set cdev state index 9 state 8750000 wr:26250000
Jan 23 22:16:30 wil93-arch thermald[1764]: Set : 93500, 87000, 9, 8750000, 26250000
Jan 23 22:16:30 wil93-arch thermald[1764]: set cdev state index 9 state 10500000 wr:24500000
Jan 23 22:16:30 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 10500000, 26250000
Jan 23 22:16:34 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:34 wil93-arch thermald[1764]: consecutive call, increment exponentially state 14000000
Jan 23 22:16:34 wil93-arch thermald[1764]: set cdev state index 9 state 14000000 wr:21000000
Jan 23 22:16:34 wil93-arch thermald[1764]: Set : 87000, 88000, 9, 14000000, 26250000
Jan 23 22:16:38 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:38 wil93-arch thermald[1764]: consecutive call, increment exponentially state 17500000
Jan 23 22:16:38 wil93-arch thermald[1764]: set cdev state index 9 state 17500000 wr:17500000
Jan 23 22:16:38 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 17500000, 26250000
Jan 23 22:16:42 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:42 wil93-arch thermald[1764]: consecutive call, increment exponentially state 24500000
Jan 23 22:16:42 wil93-arch thermald[1764]: set cdev state index 9 state 24500000 wr:10500000
Jan 23 22:16:42 wil93-arch thermald[1764]: Set : 87000, 88000, 9, 24500000, 26250000
Jan 23 22:16:46 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:46 wil93-arch thermald[1764]: consecutive call, increment exponentially state 38500000
Jan 23 22:16:46 wil93-arch thermald[1764]: set cdev state index 9 state 26250000 wr:8750000
Jan 23 22:16:46 wil93-arch thermald[1764]: Set : 87000, 87000, 9, 26250000, 26250000
Jan 23 22:16:50 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:50 wil93-arch thermald[1764]: Set : 87000, 87000, 10, 1, 10
Jan 23 22:16:54 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:54 wil93-arch thermald[1764]: consecutive call, increment exponentially state 3
Jan 23 22:16:54 wil93-arch thermald[1764]: turbo disabled
Jan 23 22:16:54 wil93-arch thermald[1764]: Set : 87000, 87000, 10, 3, 10
Jan 23 22:16:58 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:16:58 wil93-arch thermald[1764]: consecutive call, increment exponentially state 5
Jan 23 22:16:58 wil93-arch thermald[1764]: Set : 87000, 87000, 10, 5, 10
Jan 23 22:17:02 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:17:02 wil93-arch thermald[1764]: consecutive call, increment exponentially state 9
Jan 23 22:17:02 wil93-arch thermald[1764]: Set : 87000, 88000, 10, 9, 10
Jan 23 22:17:06 wil93-arch thermald[1764]: skip to reduce current state as this is controlled by two zone or trip actions and one is still on 1:2
Jan 23 22:17:06 wil93-arch thermald[1764]: consecutive call, increment exponentially state 17
Jan 23 22:17:06 wil93-arch thermald[1764]: Set : 87000, 87000, 10, 10, 10
```

What do you think about it? Could it be a thermald issue?

**Comment by spandruvada** [comment]
On Fri, 2015-01-23 at 17:42 -0800, William Di Luigi wrote:
> ( see also https://bbs.archlinux.org/viewtopic.php?pid=1495613 )
> 
> Lately my laptop started freezing. For example, I am watching a video
> (VCL, youtube, doesn't matter..) and sometimes my laptop will just
> hang, endlessly repeating the last second (or so) of audio (while the
> video, as well as the mouse pointer and everything else, is stuck). It
> also happens when I am literally doing nothing (I go back to the
> laptop after being away and it's stuck).
> 
> I am wondering if thermald may be the cause. I use Archlinux, this is
> the log from journalctl before the forced shutdown:
> 
Your laptop cpu temperature is 86C, so thermald is controlling the
temperature, by reducing performance.
I guess if you stop thermald, your laptop will power off anyway.

You can try to increase the action temperature to a higher temperature
E.g. 93C, by sending dbus command

dbus-send --system
--dest=org.freedesktop.thermald /org/freedesktop/thermald
org.freedesktop.thermald.SetUserPassiveTemperature 93000

**Comment by spandruvada** [comment]
Try this first.
Search thermal-cpu-cdev-order.xml from root directory. This may
be /usr/local/etc/thermald or /usr/etc/thermald or /etc/thermald

Delete line 
        <CoolingDevice>intel_powerclamp</CoolingDevice>


And reboot.

Also send output of
	uname -a

some changes in 3.18 kernel broke one kernel driver (power clamp
driver), which is used by thermald. This was fixed in later versions,
but I don't know which kernel version it made it to.

Thanks,
Srinivas

**Comment by rwappler** [comment]
hello,

first of all, I observe similar behaviour. The machine seems to freeze, when idle injectors kick in. I therefore stopped thermald and since then, I do not have any problems. I will check, whether it is enough to disable the powerclamp driver. If, so kernel 3.18.3 is still broken.

Linux darya 3.18.3-1 #1 SMP PREEMPT Sat Jan 17 23:30:27 CET 2015 x86_64 Intel(R) Core(TM) i7 CPU L 640 @ 2.13GHz GenuineIntel GNU/Linux

I use version 1.3 of thermald.

Cheers

**Comment by rwappler** [comment]
Disabling intel_powerclamp is promising. First tests have not shown any freeze.

**Comment by wil93** [comment]
Same here: disabling intel_powerclamp seems to fix it. Also:

    > $ uname -a
    Linux wil93-arch 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux

**Comment by spandruvada** [comment]
On Sun, 2015-01-25 at 06:09 -0800, William Di Luigi wrote:
> Same here: disabling intel_powerclamp seems to fix it. Also:

We need to patch the kernel with the fix. I don't know who is
maintaining kernel in Arch Linux. If you cab get in touch, I can point
to change.

Thanks,
Srinivas

**Comment by RJVB** [comment]
I have the same question but a different kernel (and probaby hardware); could thermald be the reason for this crash
https://arstechnica.com/civis/viewtopic.php?f=16&t=1322553 ?

I use the Ubuntu 14.04 thermald package @1.4.3-5~14.04.4, and I'm not seeing any adverse effects of disabling thermald for now. In fact  temperatures might even be a tad lower - which is probably impossible and just my imagination.

Running a C++ build job on 3 cores:
[code]
> sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:        +65.0°C  (crit = +120.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +64.0°C  (high = +90.0°C, crit = +90.0°C)
Core 1:       +65.0°C  (high = +90.0°C, crit = +90.0°C)
Core 2:       +59.0°C  (high = +90.0°C, crit = +90.0°C)
Core 3:       +65.0°C  (high = +90.0°C, crit = +90.0°C)

soc_dts0-virtual-0
Adapter: Virtual device
temp1:        +52.0°C  

soc_dts1-virtual-0
Adapter: Virtual device
temp1:        +52.0°C  
[/code]

**Comment by spandruvada** [comment]
On Tue, 2016-07-19 at 05:19 -0700, René Bertin wrote:
> I have the same question but a different kernel (and probaby
> hardware); could thermald be the reason for this crash
> https://arstechnica.com/civis/viewtopic.php?f=16&t=1322553 ?

User space process can't stall CPU. This can be done by some kernel
drivers. thermald happen to be user space when this stall happened.

**Comment by RJVB** [comment]
On Tuesday July 19 2016 08:56:00 Srinivas Pandruvada wrote:

>User space process can't stall CPU. This can be done by some kernel
>drivers. thermald happen to be user space when this stall happened.

Call me ignorant, but if a process running as root can shutdown or reboot the machine, why could it not stall the CPU - when going through the proper channels of course? Or on the contrary, by doing something it shouldn't have done, triggering a bug somewhere. Given my impression of current support for Braswell CPUs I'm inclined to assume something like that is happening, but I may never know unless I figure out how to reproduce the issue on demand ... or find someone who already has the solution.

R.

**Comment by spandruvada** [comment]
On Tue, 2016-07-19 at 10:51 -0700, René Bertin wrote:
On Tuesday July 19 2016 08:56:00 Srinivas Pandruvada wrote:

>User space process can't stall CPU. This can be done by some kernel
>drivers. thermald happen to be user space when this stall happened.

Call me ignorant, but if a process running as root can shutdown or reboot the machine, why could it not stall the CPU - when going through the proper channels of course?
Scheduler will not allow this. Some other process will get chance to run.

Or on the contrary, by doing something it shouldn't have done, triggering a bug somewhere. Given my impression of current support for Braswell CPUs I'm inclined to assume something like that is happening, but I may never know unless I figure out how to reproduce the issue on demand ... or find someone who already has the solution.
You need dmesg for this when the stall happens.


R.

**Comment by RJVB** [comment]
On Tuesday July 19 2016 10:59:20 Srinivas Pandruvada wrote:

>You need dmesg for this when the stall happens.


[There's a hole in my bucket ... :)]

Evidently. Except that when the stall happens I can no longer do anything other than power-cycle the machine to get it unstalled. Hence the screenshot (as in photo of my screen) in the post on Ars.

I'm not sure why the kernel output seen in that photo isn't stored in a logfile ... or maybe that's because ZFS never gets the chance to commit the output to disk.

R

**Comment by spandruvada** [comment]
On Tue, 2016-07-19 at 11:15 -0700, René Bertin wrote:
> On Tuesday July 19 2016 10:59:20 Srinivas Pandruvada wrote:
> 
> >You need dmesg for this when the stall happens.
> 
> 
> [There's a hole in my bucket ... :)]
> 
> Evidently. Except that when the stall happens I can no longer do
> anything other than power-cycle the machine to get it unstalled.
> Hence the screenshot (as in photo of my screen) in the post on Ars.
> 
Try magic SysRq key if you can.

**Comment by RJVB** [comment]
On Tuesday July 19 2016 11:23:38 Srinivas Pandruvada wrote:

>Try magic SysRq key if you can.

If that's on the same key as Print Screen it didn't do anything the last time. I think I tried all keys and the usual combinations like Ctrl-Alt-Del, but will of course try again next time I get a freeze.

R.

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
